### ISSUE TITLE
Subpage for the stories

### ISSUE THREAD

**Issue by marekbrze** [ocavue/astrobook#51]
Hi!

I really like your project! 

It would be great to be able to add this to the existing project and generate Astrobook on the selected subpage - like "example.com/astrobook".

**Comment by marekbrze** [comment]
I can see there is an "injectRoute" option in the docs

https://docs.astro.build/en/reference/integrations-reference/#injectroute-option

**Comment by ocavue** [comment]
Hi. You can implement this by adding `base: '/astrobook'` to your `astro.config.mjs` file. Check [Astro's docs](https://docs.astro.build/en/reference/configuration-reference/#base) for more information.

**Comment by marekbrze** [comment]
@ocavue but isn't this option for the WHOLE Astro project?

I was thinking about setting path for the integration itself and deciding where it should display.

My perfect use case is:
- I have an existing blog astro project
- I add "Astrobook" to this existing project
- I set "/astrobook" for the Astrobook integration and "devOnly" flag to `true`
- When I run `npm run dev` I have my Astrobook shown on the `/astrbook` path as a help when developing components
- When I build the blog project the Astrobook shouldn't be generated

**Comment by ocavue** [comment]
I see. You want to integrate astrobook into an existing astro project. Let me reopen this issue.

**Comment by marekbrze** [comment]
@ocavue Awesome! I will test it today ❤️🙌
