### ISSUE TITLE
Ability to add custom css

### ISSUE THREAD

**Issue by florian-lefebvre** [ocavue/astrobook#62]
Hi, awesome project you have there!

I do have a feature request: when you develop a component, it often has its own css (that you can import directly) but it also relies on some global css (eg. fonts, tailwind). Right now, it's recommended to import the global css for each component.

My suggestion would be to accept some custom css in the integration config, and make it so it's imported in the routes you inject.

It's easy to do with a virtual module, so I can implement it if you think it's great for your project. Thank you!

**Comment by ocavue** [comment]
Storybook has `.storybook/preview.js` and `.storybook/preview-head.html`, where you can add global CSS, font, script etc ([docs link](https://storybook.js.org/docs/configure/story-rendering)). We could provide some kind of injections that allow users to inject not only CSS, but also something else. Maybe an inject point that can insert an Astro component into `<head>`.

**Comment by spokospace** [comment]
Do you have any example of using unocss? 

I tried to import it via .storybook/previev.js but it still doesn't work...

**Comment by ocavue** [comment]
> I tried to import it via .storybook/previev.js but it still doesn't work...

Astrobook currently doesn't support `.storybook/previev.js`. You will need to import related CSS files in your component files, for example:

```jsx
// src/components/MyButton.jsx

import "../styles/global.css"

export default function MyButton () {
  return <button>...</button>
}
```

**Comment by morneluckybeard** [comment]
I was able to inject my css globally using scss preprocessorOptions, for my use-case this works perfectly.

```
// https://astro.build/config
export default defineConfig({
  integrations: [
    react({ include: ['**/react/*'] }),
    astrobook({ directory: 'src/components' }),
  ],
  output: 'static',
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: `@import "${resolve(
            './src/lib/theme/theme.min.css'
          )}";`,
        },
      },
    },
  },
})
```

**Comment by ocavue** [comment]
The latest astrobook@0.7.0 adds a new `head` option that can be used to add custom CSS.

**Comment by ocavue** [comment]
@morneluckybeard You can create a custom head Astro component, and use MutationObserver to watch the color schema and update data attribute in the `<html>` element. 

```astro
<!-- src/components/CustomHead.astro -->
<script>
function updateDataThemeAttr() {
  const html = document.documentElement
  // Astrobook will set the 'dark' class name to the <html>
  const isDark = html.classList.contains("dark")
  console.log("isDark", isDark)
  html.setAttribute('data-theme', isDark ? "dark" : "light")
}

const observer = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutationRecord) {
        console.log('style changed!', mutationRecord);
        updateDataThemeAttr()
    });    
});

observer.observe(document.documentElement, { attributes : true, attributeFilter : ['class'] });

updateDataThemeAttr()
</script>
```

Here is an online example: https://stackblitz.com/edit/github-wmp8wmyb-jnyzwo4f?file=src%2Fcomponents%2FTypography.astro
