### ISSUE TITLE
Tailwind styles not applying

### ISSUE THREAD

**Issue by mikelgmh** [ocavue/astrobook#67]
The component shown in Astrobook has different styles compared to the one used in my project. It seems that Tailwind CSS and Daisy UI styles are not working properly in Astrobook.

To reproduce this issue, try to add some Tailwind styles to a component via class. For example, `rounded-[30px]` won't apply any border radius in Astrobook.

**Comment by ocavue** [comment]
I cannot reproduce this issue. TailwindCSS seems to work fine with Astrobook.

![CleanShot 2024-12-04 at 12 52 32@2x](https://github.com/user-attachments/assets/9cb38569-7857-41ba-88af-669576f1485d)

You can check the source code of the screenshot above here: 

https://stackblitz.com/edit/github-pwxiie?file=src%2Fcomponents%2Freact%2FReactCounter.tsx

**Comment by ocavue** [comment]
(I closed this issue for now but I'd be happy to reopen it if you can provide a reproduction.)
