### ISSUE TITLE
Building the project using custom build settings crashes

### ISSUE THREAD

**Issue by mikelgmh** [ocavue/astrobook#86]
Runing `npm run build` using Astro 4.x crashes  when adding custom build settings in `astro.config.mjs`:

> The requested module '../../../../assets/Header.stories.js' does not provide an export named 'B'

```
 vite: {
    build: {
      rollupOptions: {
        output: {
          entryFileNames: 'assets/[name].js',
          chunkFileNames: 'assets/[name].js',
          assetFileNames: 'assets/[name].[ext]'
        }
      }
    }
  }
```

![image](https://github.com/user-attachments/assets/77651650-3c78-4749-a128-2b230894f130)

**Comment by ocavue** [comment]
Could you provide a minimal reproduction?

**Comment by mikelgmh** [comment]
Here's a reproduction, but I found that there's a warning that is not showing in the rest of the editors when importing the astro component in the stories file.

[Stackblitz](https://stackblitz.com/edit/withastro-astro-bpjzxkd4?file=src%2Fcomponents%2FWelcome.stories.ts)

**Comment by ocavue** [comment]
Thanks for your reproduction. In fact I can reproduce this error without using `astrobook`. 

1. Open https://stackblitz.com/github/issueset/astro4-astrobook-86?file=astro.config.mjs. This is an Astro project based on your repo, but get `astrobook` removed.
2. Run `pnpm run build`
3. You can find `dist/assets/chunk-Welcome.stories.js` and `dist/assets/entry-Welcome.stories.js`. Notice that these two files have the same value `Welcome.stories` for placeholder `[name]`.
4. Open `astro.config.mjs`. Change both `entryFileNames` and `chunkFileNames` to `assets/[name].js`. 
5. Run `pnpm run build` again. The following error will throw:
   
   ```
   The requested module '../assets/Welcome.stories.js' does not provide an export named 'W'
   ```

Although I don't fully understand what's happening under the hood, it seems that it's not a good idea to use set `entryFileNames` and `chunkFileNames` as `'assets/[name].js'`. Adding `[hash]` can resolve the issue, like

```
entryFileNames: 'assets/[name].js',
chunkFileNames: 'assets/[name]-[hash].js',
assetFileNames: 'assets/[name].[ext]'
```

**Comment by ocavue** [comment]
Is there any reason why you have to remove the default `[hash]` from `entryFileNames`, `chunkFileNames` and `assetFileNames`?

**Comment by mikelgmh** [comment]
It was required for my team and I found these options on Stackoverflow, but I guess I can find another workarounf for this. Closing as this is not related with Astrobook as you reproduced the issue without it :)
